[package]
name = "elastic_reqwest"
version = "0.20.10"
authors = ["Ashley Mannix <ashleymannix@live.com.au>", "Stephan Buys <stephan.buys@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A lightweight implementation of the Elasticsearch API based on reqwest."
documentation = "https://docs.rs/elastic_reqwest/"
repository = "https://github.com/elastic-rs/elastic"
readme = "README.md"

[dependencies]
serde = "~1"
elastic_requests = { path = "../requests" }
elastic_responses = { path = "../responses" }
reqwest = { version = "~0.9", features = ["hyper-011"] }
url = "~1"
bytes = "~0.4.5"
tokio = "0.1"
futures = "~0.1.16"
serde_json = "~1"
quick-error = "~1"

[dev-dependencies]
json_str = "^0.*"
